### ISSUE TITLE
function returns a coroutine instead a value

### ISSUE THREAD

**Issue by franckinux** [zzzsochi/aiompd#6]
The get_status method simply return self._status but its definition is async get_status(...).
An async method not containing any await keyword returns a coroutine instead a value.

**Comment by zzzsochi** [comment]
Everything is a little more complicated.
``get_status`` decorated by ``lock_and_status``. Watch this decorator.  :-)

**Comment by franckinux** [comment]
OK,read.

I'm receiving a coroutine instead of a Status object from the get_status 
method. This is my point.

Either self._status is returned by _get_status as a coroutine or the 
decorator makes the change... Unfortunately, I have no time for 
debugging now.

Furthermore, the duration field is a string representing a float. Thus, 
an exception is raised in status_from_raw when converting the string to 
an int...

Franck
