### ISSUE TITLE
Clarify relation to python-mpd2 which comes with async support

### ISSUE THREAD

**Issue by varac** [zzzsochi/aiompd#7]
https://github.com/Mic92/python-mpd2/blob/master/mpd/asyncio.py brings asyncio support to mpd2, so I wonder if this project is obsolete now ? How do they differ ?

**Comment by zzzsochi** [comment]
This is a difficult question.  :-)
This project is my first probe of asyncio for my RPi. I use it at home. And I know people how use it too. Project is not obsolete — it's freeze for better days. I see the #5 and will fix it in this year.

P.S. I don't know who real needed asynchronous interface to mpd. We are crazy programmers!

**Comment by zzzsochi** [comment]
Oh yes... I don't looked mpd2.   :-)
